tegacodess/Medlorix

src/hospitalApplication.html, styles/doctorApplication.css, styles/hospitalApplication.css
worked on the responsiveness for both the doctor application and hospital application pages
=> Responsiveness for both the doctor application and hospital application pages

src/services.html, styles/service.css
Responsiveness for Sevice page done
=> Responsiveness for Sevice page

src/clinicSearch.html, src/clinicSearchAfter.html, src/doctorApplication.html, src/hospitalApplication.html, styles/chatbot.css, styles/clinicSearch.css, styles/clinicSearchAfter.css, styles/doctorApplication.css, styles/hospitalApplication.css
Chore: connecting the Hamburger menu for mobile screens
=> connecting the Hamburger menu for mobile screens

contact.js, src/career.html, src/clinicSearch.html, src/clinicSearchAfter.html, src/contact.html, src/faq.html, styles/career.css
career page responsiveness and Contact page form submission working
=> Chore: career page responsiveness and Contact page form submission

index.html, src/about.html, styles/about.css, styles/index.css, styles/service.css
Worked on the About us hamburger menu
=> About us hamburger menu

styles/contact.css, styles/index.css, subcribe.js
Validating email before subscribing
=> Validating email before subscribing

src/services.html, styles/service.css
Chore: Modified the Heading and MVP
=> Chore: Modified the Heading and MVP

src/services.html
Chore: Added target=_blank to the card
=> Chore: Added target=_blank to the card

src/services.html
Chore: ReadMore button linked for reading
=> Chore: ReadMore button linked for reading

static/css/FAQ.css, static/css/about.css, static/css/bookAppointment.css, static/css/career.css, static/css/clinicSearch.css, static/css/clinicSearchAfter.css, static/css/contact.css, static/css/index.css, static/css/service.css, templates/index.html
made adjustments to the footer of all pages
=> Footer adjustments

templates/index.html, templates/sign-up.html
Chore: Removed the partner card and modified the sign up form
=> Chore: Removed the partner card and modified the sign up form

static/css/terms.css, templates/terms.html
created new terms and condition page
=> Terms and condition

templates/about.html, templates/bookAppointment.html, templates/career.html, templates/clinicSearch.html, templates/clinicSearchAfter.html, templates/contact.html, templates/faq.html, templates/index.html, templates/login.html, templates/services.html, templates/sign-up.html, templates/sign-up2.html
Linked the terms and conditions page
=> Terms and conditions page linking

templates/about.html, templates/bookAppointment.html, templates/career.html, templates/clinicSearch.html, templates/clinicSearchAfter.html, templates/contact.html, templates/faq.html, templates/index.html, templates/login.html, templates/services.html, templates/sign-up.html, templates/sign-up2.html, templates/terms.html
updated linking of terms and condition
=> updated linking of terms and condition

app.py, static/css/FAQ.css, static/css/about.css, static/css/bookAppointment.css, static/css/career.css, static/css/clinicSearch.css, static/css/clinicSearchAfter.css, static/css/contact.css, static/css/index.css, static/css/service.css, templates/index.html
Relinking of Terms and condition to all pages
=> Relinking of Terms and condition to all pages

static/css/FAQ.css, static/css/about.css, static/css/bookAppointment.css, static/css/career.css, static/css/clinicSearch.css, static/css/clinicSearchAfter.css, static/css/contact.css, static/css/index.css, static/css/service.css, templates/index.html
made changes on the service card adjustment and suscribe button adjustment
=> service card adjustment and suscribe button adjustment

static/css/index.css, static/css/login.css, templates/index.html
adjusted some styling and added linkage for terms page
=> adjustments of styling

static/js/hospitalSearch.js
Chore: Hospital search modified(City search optional)
=> Chore: Hospital search modified(City search optional

app.py, templates/hospitalApplication.html, templates/index.html, templates/login.html, templates/sign-up.html
Chore: Modified the termsPage and it's routing
=> Chore: Modified the termsPage and it's routing

templates/about.html, templates/career.html, templates/chatbot.html, templates/clinicSearch.html, templates/contact.html, templates/doctorApplication.html, templates/faq.html, templates/hospitalApplication.html, templates/index.html, templates/services.html
Chore: Modified the pages and linked them together awaiting routing
=> Chore: Modified the pages and linked them together awaiting routing

templates/bookAppointment.html, templates/index.html, templates/services.html
Chore: Modified the images & icons not displaying
=> Chore: Modified the images & icons not displaying

templates/services.html, templates/terms.html
Chore:modified the termsPage and servicesPage
=> Chore:modified the termsPage and servicesPage

static/css/adminSignIn.css, templates/adminSignIn.html, templates/doctorApplication.html, templates/hospitalApplication.html
Chore:Developed the AdminSignInPage
=> Chore:Developed the AdminSignInPage

templates/adminAppointment.html, templates/adminDoctors.html, templates/adminPatients.html, templates/adminRequests.html
Chore: Linked the adminPages together
=> Chore: Linked the adminPages together

static/css/adminAppointment.css, static/css/adminDoctors.css, static/css/adminPatients.css, static/css/adminRequests.css, templates/adminRequests.html
=> responsivess for admin pages

static/js/contact.js, templates/contact.html, templates/faq.html
Using Team Apex email for contactus
=> Using Team Apex email for contactus

templates/bookAppointment.html, templates/career.html, templates/contact.html, templates/index.html, templates/services.html, templates/sign-up.html
=> Chore:Modified some pages
